[build]
  builder = "nixpacks"
  buildCommand = "npm run build"
  installCommand = "npm install"
  startCommand = "npm start"

[deploy]
  startCommand = "node backend/src/bootstrap.js"

[env]
  AWS_REGION = "ap-south-1"
  AWS_S3_BUCKET = "hdb-s3-bucket-20250919"

